<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DBSessionStorage\Module'            => __DIR__ . '/Module.php',
    'DBSessionStorage\Storage\DBStorage' => __DIR__ . '/src/Storage/DBStorage.php',
);