<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DBSessionStorage\Module'                   => __DIR__ . '/Module.php',
  'DBSessionStorage\Factory\DBStorageFactory' => __DIR__ . '/src/Factory/DBStorageFactory.php',
  'DBSessionStorage\Storage\DBStorage'        => __DIR__ . '/src/Storage/DBStorage.php',
);
